global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8000']
  - job_name: 'locust'
    static_configs:
      - targets: ['locust:8089']